# We're just using a "stubbed out" Travis right now so we can
# use Homu <https://github.com/barosl/homu> to auto-squash
# etc.
# @jsilhan suggested pulling down a Fedora docker image as
# a tester.
language: c
install: true
script: test '!' -f broken.txt

notifications:
  webhooks: http://escher.verbum.org:54856/travis
  email: false

branches:
  only:
    - auto
